print("This Program helps you to Calculate Credit Percentage and And Regular Percentage")
print("Semester 1 Marks")
a = int(input("Please input your Applied Mathematics - I Marks"))
b = int(input("Please input your Applied Physics - I Marks"))
c = int(input("Please input your Manufacturing Processes Marks"))
d = int(input("Please input your Electrical Technology Marks"))
e = int(input("Please input your Human Values and Professional Ethics - I Marks"))
f = int(input("Please input your Fundamentals of Computing Marks"))
g = int(input("Please input your Applied Chemistry Marks"))
h = int(input("Please input your Applied Physics Lab - I Marks"))
i = int(input("Please input your Electrical Technology Lab Marks"))
j = int(input("Please input your Workshop Practice Marks"))
k = int(input("Please input your Fundamentals of Computing Lab Marks"))
l = int(input("Please input your Engineering Graphics Lab Marks"))
m = int(input("Please input your Applied Chemistry Lab Marks"))
print("Semester 2 Marks")
n = int(input("Please input your Applied Mathematics - II Marks"))
o = int(input("Please input your Applied Physics - II Marks"))
p = int(input("Please input your ELECTRONIC DEVICES Marks"))
q = int(input("Please input your INTRODUCTION TO PROGRAMMING Marks"))
r = int(input("Please input your ENGINEERING MECHANICS Marks"))
s = int(input("Please input your COMMUNICATIONS SKILLS Marks"))
t = int(input("Please input your ENVIRONMENTAL STUDIES Marks"))
u = int(input("Please input your APPLIED PHYSICS LAB-II Marks"))
v = int(input("Please input your PROGRAMMING LAB Marks"))
w = int(input("Please input your ELECTRONIC DEVICES LAB Marks"))
x = int(input("Please input your ENGINEERING MECHANICS LAB Marks"))
y = int(input("Please input your ENVIRONMENTAL STUDIES LAB Marks"))

reg_percentage = (a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y)/25

cre_percentage = (a*4+b*3+c*3+d*3+e*1+f*2+g*3+h+i+j*2+k+l*2+m+n*4+o*3+p*3+q*3+r*3+s*3+t*3+u+v+w+x+y)/54

print(f"Your Regular Percentage is {reg_percentage}")
print(f"Your Credit Percentage is {cre_percentage}")